version: 2
updates:
    - package-ecosystem: "nuget"
      directory: "/Source"
      schedule:
        interval: "daily"
      ignore:
        - dependency-name: "Cake.Core"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "daily"
