image: Visual Studio 2022

branches:
    except:
        - ci/travis
        - /dependabot\/.*/
skip_commits:
    files:
        - '*.md'
        - 'LICENSE'
        - '.travis.yml'

install:
  - choco install dotnetcore-3.1-sdk -y
  - choco install dotnet-5.0-sdk -y
  - choco install dotnet-6.0-runtime dotnet-6.0-sdk -y

build: off
test: off

build_script:
    - ps: .\build.ps1 --target=CI --verbosity=Diagnostic

cache:
    - 'tools -> .config/dotnet-tools.json,setup.cake,.build/sonarcloud.cake'
