image: Visual Studio 2019
matrix:
    fast_finish: true
environment:
    APPVEYOR_YML_DISABLE_PS_LINUX: true
branches:
    except:
        - ci/travis
        - /dependabot\/.*/
skip_commits:
    files:
        - '*.md'
        - 'LICENSE'
        - '.travis.yml'
skip_branch_with_pr: true

for:
-
    matrix:
        only:
            - image: Ubuntu
    skip_tags: true
    install:
        - sudo apt-get update || echo "Update failed, ignoring..."
        - sudo apt-get install -y libgit2-dev

build: off
test: off

build_script:
    - pwsh: .\build.ps1 --target=CI --verbosity=Diagnostic

cache:
    - 'tools -> .config/dotnet-tools.json,setup.cake,.build/sonarcloud.cake'
