image: Visual Studio 2019

branches:
    except:
        - ci/travis
        - /dependabot\/.*/
skip_commits:
    files:
        - '*.md'
        - 'LICENSE'
        - '.travis.yml'

build: off
test: off

build_script:
    - pwsh: .\build.ps1 --target=CI --verbosity=Diagnostic

cache:
    - 'tools -> .config/dotnet-tools.json,setup.cake,.build/sonarcloud.cake'
