image:
#    - macos
    - Ubuntu
    - Visual Studio 2017
matrix:
    fast_finish: true
environment:
    APPVEYOR_YML_DISABLE_PS_LINUX: true
branches:
    except:
        - ci/travis
        - /dependabot\/.*/
skip_commits:
    files:
        - '*.md'
        - 'LICENSE'
        - '.travis.yml'

for:
-
    matrix:
        only:
            - image: Ubuntu
    install:
        - git submodule update --init
        - sudo apt-get update && sudo apt-get install -y libgit2-dev

install:
    - git submodule update --init

build: off
test: off

build_script:
    - pwsh: .\build.ps1 --target=ContinuousIntegration --verbosity=Diagnostic

cache:
    - 'tools -> build.config,setup.cake,.build/sonarcloud.cake'
    - '.dotnet -> build.config'
