name: TOC Generator

on: [push, pull_request]

jobs:
    toc:
        name: TOC Generator
        runs-on: ubuntu-latest

        steps:
            - uses: technote-space/toc-generator@v2
              with:
                TARGET_PATHS: "README.md"
                TOC_TITLE: "## Table of Contents"
                PR_TITLE: "(docs) Update TOC (${PR_MERGE_REF})"
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
